name: Excerise

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to repo
        uses: actions/checkout@v2
      - name: Linux Time command
        run: |
          date

  job2:
    runs-on: macos-latest
    steps:
      - name: Connect to repo
        uses: actions/checkout@v2
      - name: macos Time command
        run: |
          date

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: install buildpack
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
          pack -h
